server:
  port: 9999

spring:
  jpa:
    show-sql: true # 启用SQL语句的日志记录
    hibernate:
      ddl-auto: update # 设置ddl模式
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
  sql:
    init:
      mode: always
      # data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
